[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name    = "ietfdata"
version = "0.9.1"
authors = [
  {name = "Colin Perkins", email = "csp@csperkins.org"}
]
description = "Access the IETF Data Tracker and RFC Index"
readme = "README.md"
requires-python = '>=3.13'
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

dependencies = [
  "imapclient",
  "pandas",
  "pandas-stubs",
  "python-dateutil",
  "pydantic",
  "psycopg",
  "requests",
  "requests-cache",
  "mypy",
  "setuptools",
  "wheel",
  "twine",
  "keyring",
  "coverage",
  "types-six",
  "types-requests",
  "types-python-dateutil",
  "setuptools-pipfile",
]

