from typing import Any

def getenv(name: Any, default: Any): ...
def get_config_defaults(): ...
def parse_config_file(filename: Any): ...
def get_string_config_defaults(): ...

OAUTH2_REFRESH_URLS: Any

def refresh_oauth2_token(hostname: Any, client_id: Any, client_secret: Any, refresh_token: Any): ...
def get_oauth2_token(hostname: Any, client_id: Any, client_secret: Any, refresh_token: Any): ...
def create_client_from_config(conf: Any, login: bool = ...): ...

class Bunch(dict):
    def __getattr__(self, k: Any): ...
    def __setattr__(self, k: Any, v: Any) -> None: ...
