from .fixed_offset import FixedOffset as FixedOffset
from typing import Any

def parse_to_datetime(timestamp: Any, normalise: bool = ...): ...
def datetime_to_native(dt: Any): ...
def datetime_to_INTERNALDATE(dt: Any): ...
def format_criteria_date(dt: Any): ...
