from datetime import tzinfo
from typing import Any

ZERO: Any

class FixedOffset(tzinfo):
    def __init__(self, minutes: Any) -> None: ...
    def utcoffset(self, _: Any): ...
    def tzname(self, _: Any): ...
    def dst(self, _: Any): ...
    @classmethod
    def for_system(klass: Any): ...
