import imaplib
from typing import Any, Optional

def wrap_socket(sock: Any, ssl_context: Any, host: Any): ...

class IMAP4_TLS(imaplib.IMAP4):
    ssl_context: Any = ...
    def __init__(self, host: Any, port: Any, ssl_context: Any, timeout: Any) -> None: ...
    host: Any = ...
    port: Any = ...
    sock: Any = ...
    file: Any = ...
    def open(self, host: str = ..., port: Any = ..., timeout: Optional[float] = ...) -> None: ...
    def read(self, size: Any): ...
    def readline(self): ...
    def send(self, data: Any) -> None: ...
    def shutdown(self) -> None: ...
