from . import exceptions as exceptions
from typing import Any, Optional

logger: Any

def to_unicode(s: Any): ...
def to_bytes(s: Any, charset: str = ...): ...
def assert_imap_protocol(condition: Any, message: Optional[Any] = ...) -> None: ...
